# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Black Duck Security Action allows you to integrate Static Analysis Security Testing (SAST) and Software Composition Analysis (SCA) into your CI/CD pipelines.
# For more information about configuring your workflow,
# read our documentation at https://github.com/blackduck-inc/black-duck-security-scan

name: CI Black Duck security scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '42 23 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      actions: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Black Duck SCA scan
        uses: blackduck-inc/black-duck-security-scan@805cbd09e806b01907bbea0f990723c2bb85abe9
        ### Configure DETECT environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          BRIDGE_NETWORK_SSL_TRUSTALL: 'true'
        with:
          ### ---------- BLACKDUCK SCA SCANNING: REQUIRED FIELDS ----------
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}

          ### SCANNING: Optional fields
        # blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'

          ### FIX PULL REQUEST CREATION: Uncomment below to enable
        # blackducksca_fixpr_enabled: true
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when Fix PRs is enabled

          ### PULL REQUEST COMMENTS: Uncomment below to enable
        # blackducksca_prcomment_enabled: true 
        # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          blackducksca_reports_sarif_create: true # Create Black Duck SCA SARIF report and upload it as artifact
          blackducksca_upload_sarif_report: true  # Upload Black Duck SCA SARIF report in GitHub Advanced Security tab
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when blackducksca_upload_sarif_report is set as true

          ### Mark build status if policy violating issues are found
        # mark_build_status: 'success'

          ### To enabable self-signed certificates. 
        #network_ssl_trustAll: true
        #network_ssl_cert_file: '/Users/Config/cert.pem'

          ### Uncomment below configuration to add custom logic based on return status
        # - name: cmdLine
        #   id: cmdLine
        #   run: |
        #     EXIT_CODE=${{ steps.black-duck-security-scan.outputs.status }}
        #     echo "Black Duck Security Scan exit status - $EXIT_CODE"

